# Generated by Django 4.2.2 on 2023-07-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_module_remove_user_rol_reg_user_role_role_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='client_count',
        ),
        migrations.RemoveField(
            model_name='module',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='module',
            name='product_count',
        ),
        migrations.RemoveField(
            model_name='module',
            name='role_count',
        ),
        migrations.RemoveField(
            model_name='module',
            name='user_count',
        ),
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='user',
            field=models.BooleanField(default=False),
        ),
    ]
