# Generated by Django 4.2.2 on 2023-07-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_module_client_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='category',
            new_name='checkout_prd',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='client',
            new_name='com_usr',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='comment',
            new_name='dashboard',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='product',
            new_name='delete_prd',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='user',
            new_name='edit_prd',
        ),
        migrations.AddField(
            model_name='module',
            name='insert_prd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='log_usr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='sales_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='shopping_history',
            field=models.BooleanField(default=False),
        ),
    ]
