# Generated by Django 4.2.2 on 2023-07-20 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_rename_category_module_checkout_prd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='module',
        ),
        migrations.CreateModel(
            name='UserRoleModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_with_module', to='register.module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_with_role', to='register.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_modules', to='register.user')),
            ],
        ),
    ]
