# Generated by Django 4.2.2 on 2023-07-20 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_role_module_userrolemodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_custom_module', to='register.module'),
        ),
        migrations.DeleteModel(
            name='UserRoleModule',
        ),
    ]
