# Generated by Django 4.2.2 on 2023-07-21 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_user_custom_module_delete_userrolemodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_module',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_custom_module', to='register.module'),
        ),
    ]
