# Generated by Django 4.2.2 on 2023-07-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_module_settings_alter_user_custom_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='audit',
            field=models.BooleanField(default=False),
        ),
    ]
