# Generated by Django 4.2.2 on 2023-07-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_module_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='products_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='users_list',
            field=models.BooleanField(default=False),
        ),
    ]
