# Generated by Django 4.2.1 on 2023-07-04 02:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_prd', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam_prd', models.CharField(max_length=100)),
                ('prc_prd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img_prd', models.ImageField(default='product_images/default.gif', upload_to='product_images')),
                ('desc_prd', models.TextField(blank=True, null=True)),
                ('qty_prd', models.PositiveIntegerField(default=0)),
                ('fec_prd', models.DateTimeField(default=django.utils.timezone.now)),
                ('del_prd', models.IntegerField(default=1)),
                ('cat_prd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_com', models.TextField()),
                ('fec_com', models.DateTimeField(default=django.utils.timezone.now)),
                ('prd_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product')),
            ],
        ),
    ]
