# Generated by Django 4.2.2 on 2023-07-15 20:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_rename_category_module_checkout_prd_and_more'),
        ('products', '0002_comment_nom_com'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_ord', models.DateTimeField(default=django.utils.timezone.now)),
                ('sub_iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tot_ord', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='register.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_prd', models.PositiveIntegerField(default=0)),
                ('sub_prd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_ord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='products.order')),
                ('id_prd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='products.product')),
            ],
        ),
    ]
