# Generated by Django 4.2.2 on 2023-07-25 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_orderaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaudit',
            name='action',
            field=models.CharField(choices=[('C', 'Created'), ('U', 'Updated'), ('D', 'Deleted'), ('R', 'Restore')], max_length=1),
        ),
        migrations.CreateModel(
            name='DeletedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam_prd', models.CharField(max_length=100)),
                ('prc_prd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img_prd', models.ImageField(default='product_images/default.gif', upload_to='product_images')),
                ('desc_prd', models.TextField(blank=True, null=True)),
                ('qty_prd', models.PositiveIntegerField(default=0)),
                ('fec_prd', models.DateTimeField()),
                ('del_prd', models.IntegerField(default=1)),
                ('cat_prd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
